options(warn=-1)
source("best.R")
# best("TX","Heart Attack")
# best("TX", "heart failure")
# best("MD", "heart attack")
# best("MD", "pneumonia")
best("BB", "heart attack")
best("NY", "hert attack")
